/**
 * Nano Prompts — VOID illustration prompt library (PR-G / PR-H / PR-I / PR-J)
 *
 * Single source of truth for VOID-side image generation. Each NanoPrompt
 * declares its provider so the dispatcher can route paid hero slots to
 * Replicate FLUX 1.1 Pro and free fill slots to Pollinations.
 *
 * Routing rules:
 *   - 'pollinations-flux'    → free, FLUX schnell, ~700-char URL ceiling
 *   - 'pollinations-realism' → free, photoreal-ish
 *   - 'pollinations-turbo'   → free, fastest, lowest quality
 *   - 'pollinations-gptimage' → free, OpenAI-tier composition
 *   - 'replicate-flux-pro'   → paid (~$0.04/img), serves from /public/void/<key>.jpg
 *   - 'replicate-flux-dev'   → paid stub
 *   - 'replicate-sdxl'       → paid stub
 *   - 'replicate-imagen'     → paid stub
 *
 * Replicate-tier slots ARE NOT generated at request time. They are
 * pre-generated by `pnpm regen-images` and committed as binaries to
 * /public/void/<key>.jpg. The dispatcher simply returns the static path.
 */

export type Provider =
  | 'pollinations-flux'
  | 'pollinations-realism'
  | 'pollinations-turbo'
  | 'pollinations-gptimage'
  | 'replicate-flux-pro'
  | 'replicate-flux-dev'
  | 'replicate-sdxl'
  | 'replicate-imagen';

export interface NanoPrompt {
  /** Stable slot key. Becomes filename for replicate-* providers: /public/void/<key>.jpg */
  key: string;
  /** One-line subject summary, used for alt text and admin tooling */
  subject: string;
  /** Output width in px (request hint; Pollinations honors, Replicate may upscale) */
  width: number;
  /** Output height in px */
  height: number;
  /** Deterministic seed — keep the same seed when iterating prompt deltas; change when starting fresh */
  seed: number;
  /** Which generation provider to route through */
  provider: Provider;
  /** The full prompt sent to the model. Self-contained — no SHARED_STYLE concat for replicate-* slots */
  prompt: string;
  /** Optional negative prompt (Replicate FLUX Pro supports it; Pollinations ignores) */
  negative?: string;
  /** True if this slot is intended to be animated later (motion design, lottie, etc) */
  animated?: boolean;
}

// ---------------------------------------------------------------------------
// SHARED_STYLE (legacy 10 slots — Neopets / Beanie Babies / CN 2001 register)
// ---------------------------------------------------------------------------
// Kept for the Pollinations-tier fill slots while they live in
// void-images-flash/. Once a slot graduates to Replicate FLUX Pro it should
// switch to a self-contained prompt block.

export const SHARED_STYLE = [
  'children\'s storybook illustration, 2001-era cartoon network character art,',
  'soft pastel palette, hand-drawn ink linework with slight wobble,',
  'flat fill colors with minimal cel-shading, paper texture background tint,',
  'whimsical melancholy mascot energy, neopets / beanie babies adjacency,',
  'absolutely no photorealism, no AI sheen, no plastic 3D render, no Pixar fur',
].join(' ');

export const COMPRESSED_STYLE =
  '2001 cartoon network mascot, ink lines, flat fill, soft pastel, neopets adjacent';

// ---------------------------------------------------------------------------
// THE REGULAR — V Pro 3 (locked direction from ChatGPT reference outputs)
// ---------------------------------------------------------------------------
// Blake reviewed V Pro 1 ("too fine, no knit, smooth dome") and V Pro 2
// (corrected line weight + 3-hole mask). Then ChatGPT generated two
// reference images that nailed the direction. V3 codifies what those
// references taught us:
//
//   1. NOT a jumpsuit — Sneaky is a HOODIE character. White hoodie + white
//      shorts + Mickey-style chunky white boots + Mickey-style mitten gloves.
//   2. NOT three holes — ONE elongated horizontal almond-shaped eye-slot
//      showing both eyes side by side. The mouth area is fully covered.
//   3. RED EYES, not white-sclera-with-black-pupils. Solid glowing red ovals
//      with angry downward brow tilt.
//   4. VISIBLE knit ribbing — vertical parallel stitch lines drawn into the
//      mask fabric. This is what finally sells "knit wool" vs "smooth blob."
//   5. PURPLE saturated background, not isolated white.
//   6. DOTTED floor shadows (3-5 small grey ovals) — Magnusson signature,
//      keeps the figure feeling walk-cycle-ready, not portrait-grounded.
//
// Black mask is canonical. White-mask sibling is intentionally not encoded
// here — when we need a "stealth" variant we'll fork to a new slot key.

const THE_REGULAR_V3_PROMPT = [
  // Pose + background — set the stage first.
  'A counterculture outlaw cartoon character standing in a slight three-quarter side stance with one foot forward and a hint of swagger lean, isolated against a flat saturated purple background (no other elements, no scenery).',
  // Mask — lead with knit texture so FLUX commits to fabric.
  'He wears a thick black knit wool balaclava covering the entire head, with clearly visible vertical knit ribbing texture rendered as parallel vertical stitch line strokes drawn throughout the mask fabric.',
  'The balaclava has ONE single elongated horizontal almond-shaped eye-slot opening — a wide narrow horizontal cutout (NOT separate circular holes) revealing two glowing solid bright red eyes side by side, with an angry downward-slanted brow tilt at the inner corners.',
  'The mouth and chin area of the mask is fully covered by knit fabric — no mouth hole, no lips visible, no chin showing.',
  // Outfit — hoodie + shorts, NOT a jumpsuit.
  'Below the mask he wears a baggy plain white pullover hoodie with the hood bunched at the back of the neck (small hood bunching visible at the collar), totally flat solid white fill with absolutely no shading and no fold creases — only a single thin black outline indicating the hoodie hem at the waist and a thin outline showing the front kangaroo pocket curve.',
  'Below the hoodie he wears baggy mid-thigh white shorts (or short pants), totally flat white fill, NO crease lines, NO interior shading, NO leg muscle definition.',
  // Hands and feet — Mickey/Felix register.
  'He has big bulbous rounded white cartoon mitten gloves with NO finger separation lines (just a single curved cuff line indicating the wrist).',
  'He wears big chunky bulbous white Mickey-Mouse-style boots with rounded almost-spherical toes, NO visible laces, NO eyelets, NO shadow lines on the boot surface — just the silhouette outline.',
  // Floor anchor — dot shadows, not a single shape.
  'The ground beneath him is suggested ONLY by 3 to 5 small dark grey oval shadow dots scattered loosely on the ground plane around his feet (NOT one connected cast shadow shape, NOT a single ellipse — discrete tiny dots).',
  // Style anchor — Markus Magnusson Sneaky series, very heavy ink line.
  'Drawn in the exact style of Markus Magnusson\'s "Sneaky" character animation series: extremely thick chunky hand-drawn black ink outlines (heavy 10-pixel-equivalent line weight, much heavier than fine vector linework), confident curved lines with a subtle hand-animated wobble, flat 2D vector cartoon illustration, ZERO gradients, ZERO crosshatching, ZERO interior shading lines anywhere on the body or clothing.',
  '1920s-1930s rubberhose animation lineage — Felix the Cat, early Mickey Mouse, Cuphead — but rendered with a modern motion-design flat finish on a solid saturated purple background.',
].join(' ');

const THE_REGULAR_V3_NEGATIVE = [
  // Wrong mask anatomy.
  'no separate round eye holes, no two-circle eye holes, no three-hole balaclava, no mouth hole, no visible mouth, no visible chin,',
  'no white-sclera eyes, no eye whites, no black pupils on white (the eyes must be solid glowing red ovals with no white showing),',
  'no smooth painted dome mask without knit texture, no two-tone printed mask pattern, no domino mask, no superhero mask, no goggles, no glasses,',
  // Wrong body anatomy.
  'no jumpsuit, no coveralls, no zip-up suit, no boiler suit, no onesie, no full-body uniform,',
  'no separated fingers on gloves, no realistic five-finger hands, no flesh-tone hands,',
  'no detailed boot laces, no eyelets, no boot shadow lines, no foot creases,',
  // Wrong style.
  'no thin vector lines, no fine detail linework, no manga, no anime, no shojo,',
  'no fabric folds, no hoodie wrinkles, no body shading, no muscle definition, no contour shading,',
  'no Mickey Mouse ears, no panda ears, no animal ears of any kind,',
  'no Pixar 3D render, no plastic AI sheen, no photorealism, no gradient shading,',
  // Wrong background.
  'no isolated white background, no plain background, no studio backdrop, no scenery, no street, no buildings,',
  'no single connected cast shadow under the figure (only discrete dot shadows)',
].join(' ');

// ---------------------------------------------------------------------------
// SLOTS — exported map keyed by slot id
// ---------------------------------------------------------------------------

export const NANO_PROMPTS: Record<string, NanoPrompt> = {
  /**
   * THE REGULAR — VOID's primary mascot character.
   * Counterculture Sneaky-style outlaw in white knit balaclava + white jumpsuit.
   * Replaces / supplements MOTHIE in the hero mascot slot.
   */
  theRegular: {
    key: 'theRegular',
    subject: 'THE REGULAR — VOID mascot, Sneaky-style outlaw in black knit balaclava + white hoodie',
    width: 1152,
    height: 864, // 4:3 landscape — matches ChatGPT reference proportions
    seed: 3142, // fresh seed for V3 — ChatGPT-anchored direction is a new branch from V2
    provider: 'replicate-flux-pro',
    prompt: THE_REGULAR_V3_PROMPT,
    negative: THE_REGULAR_V3_NEGATIVE,
  },

  /**
   * MOTHIE — legacy moth mascot. Pre-generated via Replicate FLUX 1.1 Pro,
   * served from /public/void/mothie.jpg. Kept around but de-prioritized in
   * favor of THE REGULAR.
   */
  mothie: {
    key: 'mothie',
    subject: 'MOTHIE — kawaii moth mascot (legacy)',
    width: 896,
    height: 1152,
    seed: 4471,
    provider: 'replicate-flux-pro',
    prompt: [
      'A small chubby kawaii moth character with oversized fluffy wings and large round black eyes,',
      'pastel cream-colored body, soft fuzzy texture,',
      SHARED_STYLE,
    ].join(' '),
  },
};

// ---------------------------------------------------------------------------
// URL builders + dispatcher
// ---------------------------------------------------------------------------

const POLLINATIONS_BASE = 'https://image.pollinations.ai/prompt';
const URL_CEILING = 1700;

function buildPollinationsUrl(p: NanoPrompt, model: string): string {
  // Trim prompt to fit under URL ceiling once encoded + model/size/seed params.
  const params = `?width=${p.width}&height=${p.height}&seed=${p.seed}&model=${model}&nologo=true`;
  const encodedBudget = URL_CEILING - POLLINATIONS_BASE.length - params.length - 10;
  const encoded = encodeURIComponent(p.prompt);
  const trimmed =
    encoded.length > encodedBudget ? encoded.slice(0, encodedBudget) : encoded;
  return `${POLLINATIONS_BASE}/${trimmed}${params}`;
}

export const pollinationsFluxUrl = (p: NanoPrompt) => buildPollinationsUrl(p, 'flux');
export const pollinationsRealismUrl = (p: NanoPrompt) =>
  buildPollinationsUrl(p, 'flux-realism');
export const pollinationsTurboUrl = (p: NanoPrompt) => buildPollinationsUrl(p, 'turbo');
export const pollinationsGptImageUrl = (p: NanoPrompt) =>
  buildPollinationsUrl(p, 'gptimage');

/** Replicate-tier slots are pre-generated. Return the committed static path. */
export function replicateStaticUrl(p: NanoPrompt): string {
  return `/void/${p.key}.jpg`;
}

/** Master dispatcher — routes each slot to its declared provider. */
export function imageUrl(p: NanoPrompt): string {
  switch (p.provider) {
    case 'pollinations-flux':
      return pollinationsFluxUrl(p);
    case 'pollinations-realism':
      return pollinationsRealismUrl(p);
    case 'pollinations-turbo':
      return pollinationsTurboUrl(p);
    case 'pollinations-gptimage':
      return pollinationsGptImageUrl(p);
    case 'replicate-flux-pro':
    case 'replicate-flux-dev':
    case 'replicate-sdxl':
    case 'replicate-imagen':
      return replicateStaticUrl(p);
  }
}

/** Convenience: get a slot by key. Throws if missing — fail fast on typos. */
export function getNanoPrompt(key: string): NanoPrompt {
  const p = NANO_PROMPTS[key];
  if (!p) throw new Error(`[nanoPrompts] Unknown slot key: ${key}`);
  return p;
}
