/**
 * Nano Prompts — VOID illustration prompt library (PR-G / PR-H / PR-I / PR-J)
 *
 * Single source of truth for VOID-side image generation. Each NanoPrompt
 * declares its provider so the dispatcher can route paid hero slots to
 * Replicate FLUX 1.1 Pro and free fill slots to Pollinations.
 *
 * Routing rules:
 *   - 'pollinations-flux'    → free, FLUX schnell, ~700-char URL ceiling
 *   - 'pollinations-realism' → free, photoreal-ish
 *   - 'pollinations-turbo'   → free, fastest, lowest quality
 *   - 'pollinations-gptimage' → free, OpenAI-tier composition
 *   - 'replicate-flux-pro'   → paid (~$0.04/img), serves from /public/void/<key>.jpg
 *   - 'replicate-flux-dev'   → paid stub
 *   - 'replicate-sdxl'       → paid stub
 *   - 'replicate-imagen'     → paid stub
 *
 * Replicate-tier slots ARE NOT generated at request time. They are
 * pre-generated by `pnpm regen-images` and committed as binaries to
 * /public/void/<key>.jpg. The dispatcher simply returns the static path.
 */

export type Provider =
  | 'pollinations-flux'
  | 'pollinations-realism'
  | 'pollinations-turbo'
  | 'pollinations-gptimage'
  | 'replicate-flux-pro'
  | 'replicate-flux-dev'
  | 'replicate-sdxl'
  | 'replicate-imagen';

export interface NanoPrompt {
  /** Stable slot key. Becomes filename for replicate-* providers: /public/void/<key>.jpg */
  key: string;
  /** One-line subject summary, used for alt text and admin tooling */
  subject: string;
  /** Output width in px (request hint; Pollinations honors, Replicate may upscale) */
  width: number;
  /** Output height in px */
  height: number;
  /** Deterministic seed — keep the same seed when iterating prompt deltas; change when starting fresh */
  seed: number;
  /** Which generation provider to route through */
  provider: Provider;
  /** The full prompt sent to the model. Self-contained — no SHARED_STYLE concat for replicate-* slots */
  prompt: string;
  /** Optional negative prompt (Replicate FLUX Pro supports it; Pollinations ignores) */
  negative?: string;
  /** True if this slot is intended to be animated later (motion design, lottie, etc) */
  animated?: boolean;
}

// ---------------------------------------------------------------------------
// SHARED_STYLE (legacy 10 slots — Neopets / Beanie Babies / CN 2001 register)
// ---------------------------------------------------------------------------
// Kept for the Pollinations-tier fill slots while they live in
// void-images-flash/. Once a slot graduates to Replicate FLUX Pro it should
// switch to a self-contained prompt block.

export const SHARED_STYLE = [
  'children\'s storybook illustration, 2001-era cartoon network character art,',
  'soft pastel palette, hand-drawn ink linework with slight wobble,',
  'flat fill colors with minimal cel-shading, paper texture background tint,',
  'whimsical melancholy mascot energy, neopets / beanie babies adjacency,',
  'absolutely no photorealism, no AI sheen, no plastic 3D render, no Pixar fur',
].join(' ');

export const COMPRESSED_STYLE =
  '2001 cartoon network mascot, ink lines, flat fill, soft pastel, neopets adjacent';

// ---------------------------------------------------------------------------
// THE REGULAR — V Pro 2
// ---------------------------------------------------------------------------
// Blake's V1 critique: lines too fine, jumpsuit too creased, ski mask reads
// as smooth dome with printed eyes (not knit fabric with cutouts).
//
// V2 corrections baked into the prompt:
//   1. THICKER outlines — explicit "thick chunky black ink outlines" + line
//      weight reference to Markus Magnusson Sneaky-style.
//   2. MINIMAL interior detail — "flat white fill, no fold lines, no shading
//      lines, no creases" + negative reinforcement.
//   3. PROPER ski mask anatomy — leads with "knit white wool balaclava" and
//      explicitly calls out THREE distinct circular openings: two round eye
//      holes (visible eyes inside) + one round mouth hole (visible darkness
//      inside). Knit fabric must read as fabric, not painted skin.
//
// Negatives stack-ranked by failure mode observed in V1 + Pollinations runs.

const THE_REGULAR_V2_PROMPT = [
  // Lead with the mask material, not the head silhouette.
  'A 1930s rubberhose cartoon character wearing a thick knit white wool balaclava ski mask covering the entire head.',
  'The balaclava has THREE distinct circular cutout openings: two round eye holes on the upper face revealing only the eyes inside (small black dot pupils on white sclera), and one round mouth hole on the lower face revealing only solid darkness inside.',
  'The knit wool fabric is clearly visible — chunky stitched texture, slightly fuzzy edges around each cutout opening, the holes are real holes cut into fabric (not painted-on shapes).',
  // Body simplification.
  'Below the mask he wears a baggy plain white loose-fitting jumpsuit, totally flat white fill with no creases, no fold lines, no pleats, no shading, no contour lines on the body.',
  'White cuffed gloves, simple white work boots with NO visible laces and NO shadow lines on the boot surface.',
  'Standing relaxed in a slight contrapposto pose, full body shot, isolated on pure white background with one soft cast shadow on the ground beneath the boots.',
  // Style anchor — Markus Magnusson "Sneaky" series.
  'Drawn in the exact style of Markus Magnusson\'s "Sneaky" character animation series: thick chunky hand-drawn black ink outlines (heavy 8-pixel-equivalent line weight), confident curved lines with slight hand-animated wobble, flat 2D vector cartoon illustration, NO gradients, NO interior detail lines, NO crosshatching.',
  '1920s-1930s rubberhose animation lineage — Felix the Cat, early Mickey Mouse, Cuphead inspiration — but rendered with modern motion-design flat finish.',
].join(' ');

const THE_REGULAR_V2_NEGATIVE = [
  'no Mickey Mouse ears, no panda ears, no animal ears of any kind,',
  'no domino mask, no superhero mask, no goggles, no glasses, no eye paint,',
  'no smooth dome head, no plain white blob, no Baymax, no marshmallow figure,',
  'no hood, no hoodie, no pulled-up shirt collar covering the face,',
  'no jumpsuit creases, no fabric folds, no body shading, no foot shadows,',
  'no thin vector lines, no fine detail linework, no manga style, no anime,',
  'no photorealism, no 3D render, no Pixar fur, no plastic AI sheen,',
  'no skin tone visible anywhere, no exposed face, no mouth lips visible,',
  'no two-tone mask printed pattern (the mask must be solid white knit wool with three real cutout holes)',
].join(' ');

// ---------------------------------------------------------------------------
// SLOTS — exported map keyed by slot id
// ---------------------------------------------------------------------------

export const NANO_PROMPTS: Record<string, NanoPrompt> = {
  /**
   * THE REGULAR — VOID's primary mascot character.
   * Counterculture Sneaky-style outlaw in white knit balaclava + white jumpsuit.
   * Replaces / supplements MOTHIE in the hero mascot slot.
   */
  theRegular: {
    key: 'theRegular',
    subject: 'THE REGULAR — VOID mascot, Sneaky-style ski-masked figure',
    width: 896,
    height: 1152,
    seed: 2287, // fresh seed to break out of V1 composition trap
    provider: 'replicate-flux-pro',
    prompt: THE_REGULAR_V2_PROMPT,
    negative: THE_REGULAR_V2_NEGATIVE,
  },

  /**
   * MOTHIE — legacy moth mascot. Pre-generated via Replicate FLUX 1.1 Pro,
   * served from /public/void/mothie.jpg. Kept around but de-prioritized in
   * favor of THE REGULAR.
   */
  mothie: {
    key: 'mothie',
    subject: 'MOTHIE — kawaii moth mascot (legacy)',
    width: 896,
    height: 1152,
    seed: 4471,
    provider: 'replicate-flux-pro',
    prompt: [
      'A small chubby kawaii moth character with oversized fluffy wings and large round black eyes,',
      'pastel cream-colored body, soft fuzzy texture,',
      SHARED_STYLE,
    ].join(' '),
  },
};

// ---------------------------------------------------------------------------
// URL builders + dispatcher
// ---------------------------------------------------------------------------

const POLLINATIONS_BASE = 'https://image.pollinations.ai/prompt';
const URL_CEILING = 1700;

function buildPollinationsUrl(p: NanoPrompt, model: string): string {
  // Trim prompt to fit under URL ceiling once encoded + model/size/seed params.
  const params = `?width=${p.width}&height=${p.height}&seed=${p.seed}&model=${model}&nologo=true`;
  const encodedBudget = URL_CEILING - POLLINATIONS_BASE.length - params.length - 10;
  const encoded = encodeURIComponent(p.prompt);
  const trimmed =
    encoded.length > encodedBudget ? encoded.slice(0, encodedBudget) : encoded;
  return `${POLLINATIONS_BASE}/${trimmed}${params}`;
}

export const pollinationsFluxUrl = (p: NanoPrompt) => buildPollinationsUrl(p, 'flux');
export const pollinationsRealismUrl = (p: NanoPrompt) =>
  buildPollinationsUrl(p, 'flux-realism');
export const pollinationsTurboUrl = (p: NanoPrompt) => buildPollinationsUrl(p, 'turbo');
export const pollinationsGptImageUrl = (p: NanoPrompt) =>
  buildPollinationsUrl(p, 'gptimage');

/** Replicate-tier slots are pre-generated. Return the committed static path. */
export function replicateStaticUrl(p: NanoPrompt): string {
  return `/void/${p.key}.jpg`;
}

/** Master dispatcher — routes each slot to its declared provider. */
export function imageUrl(p: NanoPrompt): string {
  switch (p.provider) {
    case 'pollinations-flux':
      return pollinationsFluxUrl(p);
    case 'pollinations-realism':
      return pollinationsRealismUrl(p);
    case 'pollinations-turbo':
      return pollinationsTurboUrl(p);
    case 'pollinations-gptimage':
      return pollinationsGptImageUrl(p);
    case 'replicate-flux-pro':
    case 'replicate-flux-dev':
    case 'replicate-sdxl':
    case 'replicate-imagen':
      return replicateStaticUrl(p);
  }
}

/** Convenience: get a slot by key. Throws if missing — fail fast on typos. */
export function getNanoPrompt(key: string): NanoPrompt {
  const p = NANO_PROMPTS[key];
  if (!p) throw new Error(`[nanoPrompts] Unknown slot key: ${key}`);
  return p;
}
