/**
 * Nano Prompts — VOID illustration prompt library (PR-G / PR-H / PR-I / PR-J)
 *
 * Single source of truth for VOID-side image generation. Each NanoPrompt
 * declares its provider so the dispatcher can route paid hero slots to
 * Replicate FLUX 1.1 Pro and free fill slots to Pollinations.
 *
 * Routing rules:
 *   - 'pollinations-flux'    → free, FLUX schnell, ~700-char URL ceiling
 *   - 'pollinations-realism' → free, photoreal-ish
 *   - 'pollinations-turbo'   → free, fastest, lowest quality
 *   - 'pollinations-gptimage' → free, OpenAI-tier composition
 *   - 'replicate-flux-pro'   → paid (~$0.04/img), serves from /public/void/<key>.jpg
 *   - 'replicate-flux-dev'   → paid stub
 *   - 'replicate-sdxl'       → paid stub
 *   - 'replicate-imagen'     → paid stub
 *
 * Replicate-tier slots ARE NOT generated at request time. They are
 * pre-generated by `pnpm regen-images` and committed as binaries to
 * /public/void/<key>.jpg. The dispatcher simply returns the static path.
 */

export type Provider =
  // Free text-to-image (Pollinations.ai)
  | 'pollinations-flux'
  | 'pollinations-realism'
  | 'pollinations-turbo'
  | 'pollinations-gptimage'
  // Paid text-to-image (Replicate)
  | 'replicate-flux-pro'
  | 'replicate-flux-dev'
  | 'replicate-recraft-v3' // flat-illustration native prior — NO style ref via Replicate
  | 'replicate-sdxl'
  | 'replicate-imagen'
  // Paid image-to-image (Replicate) — requires anchorKey
  | 'replicate-flux-kontext-pro'
  // Locked binary committed to /public/void/<key>.jpg — no generation
  | 'static-asset';

/**
 * Recraft V3 style modes. Recraft's prior is purpose-built for flat
 * illustration — its `style` field tells the model which sub-prior to use.
 * `digital_illustration` is the closest match to our Sneaky/Magnusson
 * register; `vector_illustration` is a harder-edged alternative.
 */
export type RecraftStyle =
  | 'digital_illustration'
  | 'digital_illustration/2d_art_poster'
  | 'digital_illustration/2d_art_poster_2'
  | 'digital_illustration/hand_drawn'
  | 'digital_illustration/handmade_3d'
  | 'digital_illustration/grain'
  | 'vector_illustration'
  | 'vector_illustration/cartoon'
  | 'vector_illustration/flat_2'
  | 'realistic_image';

/**
 * Style anchors — committed reference images that drive image-to-image
 * generation. A slot with `provider: 'replicate-flux-kontext-pro'` references
 * one of these by key, and the regen script base64-encodes the file at
 * `diskPath` and sends it to Kontext as `input_image`.
 *
 * Workflow: save your hero/canonical character as a JPG, drop it in
 * `public/void/refs/`, then add it to STYLE_ANCHORS. Any number of variant
 * slots can target it.
 */
export interface StyleAnchor {
  /** Disk path relative to project root (used by regen script for fs read) */
  diskPath: string;
  /** Public URL path (used at request time for in-page rendering, if needed) */
  publicPath: string;
  /** What this anchor is — character + register + framing */
  description: string;
}

export const STYLE_ANCHORS: Record<string, StyleAnchor> = {
  theRegularBlack: {
    diskPath: 'public/void/refs/the-regular-black.jpg',
    publicPath: '/void/refs/the-regular-black.jpg',
    description:
      'THE REGULAR — canonical pose, black knit balaclava + white hoodie + white shorts + Mickey-style chunky white boots/gloves, glowing red eye-slot, on saturated purple background with dotted floor shadows. Locked from ChatGPT reference.',
  },
  theRegularWhite: {
    diskPath: 'public/void/refs/the-regular-white.jpg',
    publicPath: '/void/refs/the-regular-white.jpg',
    description:
      'THE REGULAR — alt "stealth" variant, all-white knit balaclava + white hoodie + white shorts on saturated purple background. Same character family as theRegularBlack, different mask color. Locked from ChatGPT reference.',
  },
};

export interface NanoPrompt {
  /** Stable slot key. Becomes filename for replicate-*/static-asset providers: /public/void/<key>.jpg */
  key: string;
  /** One-line subject summary, used for alt text and admin tooling */
  subject: string;
  /** Output width in px (request hint; Pollinations honors, Replicate may upscale) */
  width: number;
  /** Output height in px */
  height: number;
  /** Deterministic seed — keep the same seed when iterating prompt deltas; change when starting fresh */
  seed: number;
  /** Which generation provider to route through */
  provider: Provider;
  /** The full prompt sent to the model. For Kontext: describe the DELTA from the anchor, not the whole image */
  prompt: string;
  /** Optional negative prompt (Replicate FLUX Pro supports it; Kontext ignores; Pollinations ignores) */
  negative?: string;
  /** Required for `replicate-flux-kontext-pro` — which STYLE_ANCHORS entry to feed as input_image */
  anchorKey?: keyof typeof STYLE_ANCHORS;
  /** Required for `replicate-recraft-v3` — which Recraft style mode to use */
  recraftStyle?: RecraftStyle;
  /** True if this slot is intended to be animated later (motion design, lottie, etc) */
  animated?: boolean;
}

// ---------------------------------------------------------------------------
// SHARED_STYLE (legacy 10 slots — Neopets / Beanie Babies / CN 2001 register)
// ---------------------------------------------------------------------------
// Kept for the Pollinations-tier fill slots while they live in
// void-images-flash/. Once a slot graduates to Replicate FLUX Pro it should
// switch to a self-contained prompt block.

export const SHARED_STYLE = [
  'children\'s storybook illustration, 2001-era cartoon network character art,',
  'soft pastel palette, hand-drawn ink linework with slight wobble,',
  'flat fill colors with minimal cel-shading, paper texture background tint,',
  'whimsical melancholy mascot energy, neopets / beanie babies adjacency,',
  'absolutely no photorealism, no AI sheen, no plastic 3D render, no Pixar fur',
].join(' ');

export const COMPRESSED_STYLE =
  '2001 cartoon network mascot, ink lines, flat fill, soft pastel, neopets adjacent';

// ---------------------------------------------------------------------------
// THE REGULAR — V Pro 3 (locked direction from ChatGPT reference outputs)
// ---------------------------------------------------------------------------
// Blake reviewed V Pro 1 ("too fine, no knit, smooth dome") and V Pro 2
// (corrected line weight + 3-hole mask). Then ChatGPT generated two
// reference images that nailed the direction. V3 codifies what those
// references taught us:
//
//   1. NOT a jumpsuit — Sneaky is a HOODIE character. White hoodie + white
//      shorts + Mickey-style chunky white boots + Mickey-style mitten gloves.
//   2. NOT three holes — ONE elongated horizontal almond-shaped eye-slot
//      showing both eyes side by side. The mouth area is fully covered.
//   3. RED EYES, not white-sclera-with-black-pupils. Solid glowing red ovals
//      with angry downward brow tilt.
//   4. VISIBLE knit ribbing — vertical parallel stitch lines drawn into the
//      mask fabric. This is what finally sells "knit wool" vs "smooth blob."
//   5. PURPLE saturated background, not isolated white.
//   6. DOTTED floor shadows (3-5 small grey ovals) — Magnusson signature,
//      keeps the figure feeling walk-cycle-ready, not portrait-grounded.
//
// Black mask is canonical. White-mask sibling is intentionally not encoded
// here — when we need a "stealth" variant we'll fork to a new slot key.

const THE_REGULAR_V3_PROMPT = [
  // Pose + background — set the stage first.
  'A counterculture outlaw cartoon character standing in a slight three-quarter side stance with one foot forward and a hint of swagger lean, isolated against a flat saturated purple background (no other elements, no scenery).',
  // Mask — lead with knit texture so FLUX commits to fabric.
  'He wears a thick black knit wool balaclava covering the entire head, with clearly visible vertical knit ribbing texture rendered as parallel vertical stitch line strokes drawn throughout the mask fabric.',
  'The balaclava has ONE single elongated horizontal almond-shaped eye-slot opening — a wide narrow horizontal cutout (NOT separate circular holes) revealing two glowing solid bright red eyes side by side, with an angry downward-slanted brow tilt at the inner corners.',
  'The mouth and chin area of the mask is fully covered by knit fabric — no mouth hole, no lips visible, no chin showing.',
  // Outfit — hoodie + shorts, NOT a jumpsuit.
  'Below the mask he wears a baggy plain white pullover hoodie with the hood bunched at the back of the neck (small hood bunching visible at the collar), totally flat solid white fill with absolutely no shading and no fold creases — only a single thin black outline indicating the hoodie hem at the waist and a thin outline showing the front kangaroo pocket curve.',
  'Below the hoodie he wears baggy mid-thigh white shorts (or short pants), totally flat white fill, NO crease lines, NO interior shading, NO leg muscle definition.',
  // Hands and feet — Mickey/Felix register.
  'He has big bulbous rounded white cartoon mitten gloves with NO finger separation lines (just a single curved cuff line indicating the wrist).',
  'He wears big chunky bulbous white Mickey-Mouse-style boots with rounded almost-spherical toes, NO visible laces, NO eyelets, NO shadow lines on the boot surface — just the silhouette outline.',
  // Floor anchor — dot shadows, not a single shape.
  'The ground beneath him is suggested ONLY by 3 to 5 small dark grey oval shadow dots scattered loosely on the ground plane around his feet (NOT one connected cast shadow shape, NOT a single ellipse — discrete tiny dots).',
  // Style anchor — Markus Magnusson Sneaky series, very heavy ink line.
  'Drawn in the exact style of Markus Magnusson\'s "Sneaky" character animation series: extremely thick chunky hand-drawn black ink outlines (heavy 10-pixel-equivalent line weight, much heavier than fine vector linework), confident curved lines with a subtle hand-animated wobble, flat 2D vector cartoon illustration, ZERO gradients, ZERO crosshatching, ZERO interior shading lines anywhere on the body or clothing.',
  '1920s-1930s rubberhose animation lineage — Felix the Cat, early Mickey Mouse, Cuphead — but rendered with a modern motion-design flat finish on a solid saturated purple background.',
].join(' ');

const THE_REGULAR_V3_NEGATIVE = [
  // Wrong mask anatomy.
  'no separate round eye holes, no two-circle eye holes, no three-hole balaclava, no mouth hole, no visible mouth, no visible chin,',
  'no white-sclera eyes, no eye whites, no black pupils on white (the eyes must be solid glowing red ovals with no white showing),',
  'no smooth painted dome mask without knit texture, no two-tone printed mask pattern, no domino mask, no superhero mask, no goggles, no glasses,',
  // Wrong body anatomy.
  'no jumpsuit, no coveralls, no zip-up suit, no boiler suit, no onesie, no full-body uniform,',
  'no separated fingers on gloves, no realistic five-finger hands, no flesh-tone hands,',
  'no detailed boot laces, no eyelets, no boot shadow lines, no foot creases,',
  // Wrong style.
  'no thin vector lines, no fine detail linework, no manga, no anime, no shojo,',
  'no fabric folds, no hoodie wrinkles, no body shading, no muscle definition, no contour shading,',
  'no Mickey Mouse ears, no panda ears, no animal ears of any kind,',
  'no Pixar 3D render, no plastic AI sheen, no photorealism, no gradient shading,',
  // Wrong background.
  'no isolated white background, no plain background, no studio backdrop, no scenery, no street, no buildings,',
  'no single connected cast shadow under the figure (only discrete dot shadows)',
].join(' ');

// ---------------------------------------------------------------------------
// SKIN_NEGATIVES — inline coverage clause for Kontext slots
// ---------------------------------------------------------------------------
// Discovered during the like-for-like Kontext fidelity test (May 2026):
// when Kontext was given the canonical anchor and asked to reproduce it
// exactly, it hallucinated a flesh-tone gap between THE REGULAR's white
// shorts and white boots — interpreting the leg gap as "show skin" by default.
//
// Kontext IGNORES the `negative` field on slots, so negatives must live
// inline in the positive prompt. This clause is appended to every Kontext
// slot prompt that involves THE REGULAR's body. Outfit-agnostic — works
// for both hoodie+shorts AND the experimental jumpsuit variant.
const SKIN_NEGATIVES = [
  'The character is fully clothed in flat white fabric with absolutely no skin tone or flesh color visible anywhere on the body —',
  'no bare legs between shorts and boots, no bare wrists between sleeves and gloves, no bare neck between mask and hoodie,',
  'no visible knees, no visible shins, no visible forearms, no exposed human anatomy of any kind.',
].join(' ');

// ---------------------------------------------------------------------------
// TEXTURE_FINISH — subtle paper-and-ink finishing layer
// ---------------------------------------------------------------------------
// Polish layer for the canonical Magnusson register: a barely-visible paper
// substrate, the gentlest ink-bleed where heavy outlines meet the paper, and
// a trace of matte grit. Goal is "drawn on paper" — NOT a noisy filter.
//
// Use sparingly: append to slot prompts where you want hand-drawn warmth.
// Keeps the flat-fill discipline intact while killing the AI-sheen. If a
// future re-render of the canonical anchor folds this in, all Kontext-derived
// slots will inherit the finish for free via image-conditioning.
const TEXTURE_FINISH = [
  'Subtle hand-drawn paper finish — the entire image rendered as if drawn on a sheet of slightly textured cream-toned cartridge paper.',
  'A very faint barely-visible paper grain runs across the flat color fills.',
  'Where the thick black ink outlines meet the paper, there is the gentlest hint of ink bleed and a trace of irregularity in line weight (extremely subtle — just enough to feel hand-drawn, not enough to break the flat fill).',
  'A trace of matte grit across the whole surface, like a real-world drawing photographed flat.',
  'The texture is a finish layer, not a filter — flat colors must still read as flat fills, the linework must still be confident, the cartoon clarity is preserved.',
].join(' ');

// ---------------------------------------------------------------------------
// PROPERTY REGISTERS — period-correct visual style packs (PR-L)
// ---------------------------------------------------------------------------
// One register per OmniShift-world property. Composed into property slot
// prompts via spread/concat. Each is a tight period-locked recipe — references
// are Web Design Museum gallery URLs as historical anchors, not for fetching.
//
// These are REGISTERS (style packs), not prompts on their own. Always combine
// with subject-specific text in each slot.

const OMNISHIFT_REGISTER = [
  // Reference: webdesignmuseum.org/gallery/ibm-2001, oracle-in-2002, microsoft-in-2001.
  'Period-correct early-2000s corporate stock photography — IBM 2001 / Oracle 2002 / SharePoint 2001 register.',
  'Low-saturation corporate palette: muted IBM navy (#003F7F base), cool secondary cyan (#5C9BD5), cream-white background (#F4F4F4), flat black sans-serif Helvetica/Arial type, beveled chrome buttons.',
  'Shot on a 2-megapixel consumer CCD digital camera circa 2001: mild JPEG compression artifacts at the corners, slight purple chromatic aberration on dark edges, the photographic flatness of stock-corporate-catalog imagery, no bokeh, deep depth of field.',
  'Fluorescent ceiling-tube lighting casting cool slightly-greenish skin tones, minimal contrast, no rim light, no cinematic grading.',
  'Bureaucratic and lightly sinister tone — every smile is just slightly held too long, every gesture is rehearsed, the room feels like training video.',
].join(' ');

const SLEEPNET_PORTAL_REGISTER = [
  // Reference: webdesignmuseum.org/gallery/yahoo-in-1998, geocities-1999, altavista-1999.
  '1998-2001 web portal directory illustration aesthetic — Yahoo 1998 / GeoCities 1999 / AltaVista era.',
  'Hand-drawn cartoon illustration in early-Macromedia-Flash 4 register: thick black outlines, flat 4-color GIF-palette fills, mild dithering at color edges, no gradients, no anti-aliasing on inner shapes.',
  'Vibrant primary color palette — Yahoo purple (#7B0099), saturated GIF reds, GIF greens, GIF yellows, white background with no shadows.',
  'Mascot characters drawn in a friendly clip-art register — round eyes, simple smile lines, oversized hands with three fingers, slight rubberhose-cartoon flexibility but cheaper than Disney.',
  'NEVER photographic, NEVER modern vector — must look hand-traced into Photoshop 6 with the bucket-fill tool circa 1999.',
].join(' ');

const VGB_REGISTER = [
  // Reference: webdesignmuseum.org/gallery/mcdonald-s-2000, burger-king-in-2000.
  'Period-correct 1999-2003 fast-food chain marketing photography — McDonald\'s 2000 / Burger King 2000-2003 register.',
  'Oversaturated red and yellow palette (signage red #DA291C, sun-yellow #FFC72C), glamour-shot food photography with visible steam, blue-sky-clear-day backgrounds with cumulus clouds, harsh on-camera flash.',
  'Family demographic stock photography — multi-ethnic mom and dad and two kids in branded paper hats, smiling too widely at the camera, photographed in a chain-restaurant interior with red vinyl booths and yellow walls.',
  'CRITICAL OFF-NESS RULE: every image has exactly ONE subtly-wrong element — wilted brown lettuce edges on the burger, a child with a slightly too-wide smile, the tomato slice is grey instead of red, the bun is slightly asymmetric. Bake one off-ness signal into the prompt.',
  'Captured on consumer-grade flash photography circa 2001, slight overexposure on highlights, JPEG sharpening visible at the edges of fries.',
].join(' ');

const SLEEPNEWS_REGISTER = [
  // Reference: webdesignmuseum.org/gallery/bbc-news-2000, cnn-com-1998, abc-news.
  '1998-2002 online newspaper press photography aesthetic — BBC News 2000 / CNN 1998 / ABC News 1997 register.',
  'Low-resolution AP-wire press photo: grainy 35mm film grain or early digital sensor noise, slightly underexposed, color balance off (warm orange streetlight cast or cool blue fluorescent cast), natural newsprint feel.',
  'Compressed-JPEG artifacts in the dark areas, slight motion blur, news-photographer flash bouncing off surfaces, no Photoshop retouching.',
  'Subjects captured in candid pose mid-action, never posed for the camera. Composition slightly off-center, a stray lamppost or No Parking sign cropping the edge of the frame.',
  'The kind of photo that ran on B5 of a regional paper on a Tuesday morning. Caption-worthy but not memorable.',
].join(' ');

// ---------------------------------------------------------------------------
// SLOTS — exported map keyed by slot id
// ---------------------------------------------------------------------------

export const NANO_PROMPTS: Record<string, NanoPrompt> = {
  /**
   * THE REGULAR — VOID's primary mascot. Locked as static-asset (committed
   * binary) since the ChatGPT-generated reference IS the canonical version.
   * Drop the JPG at public/void/theRegular.jpg.
   *
   * The V3 prompt + negative are kept on the slot as documentation — if we
   * ever need to re-derive via FLUX, flipping `provider` to 'replicate-flux-pro'
   * is the only change needed.
   */
  theRegular: {
    key: 'theRegular',
    subject: 'THE REGULAR — VOID mascot, Sneaky-style outlaw in black knit balaclava + white hoodie',
    width: 1152,
    height: 864,
    seed: 3142,
    provider: 'static-asset',
    prompt: THE_REGULAR_V3_PROMPT, // documentation; not executed
    negative: THE_REGULAR_V3_NEGATIVE,
  },

  /**
   * THE REGULAR — SEATED variant (Kontext pilot).
   * Demonstrates image-to-image: takes the locked anchor and applies a small
   * pose delta. Use this slot to verify Kontext respects identity before
   * committing to a larger cast roll-out.
   */
  theRegularSeated: {
    key: 'theRegularSeated',
    subject: 'THE REGULAR — seated on a fire escape, smoking',
    width: 1152,
    height: 864,
    seed: 3143,
    provider: 'replicate-flux-kontext-pro',
    anchorKey: 'theRegularBlack',
    // Kontext prompts describe the DELTA, not the whole image. Anchor handles identity.
    prompt: [
      'Same exact character from the reference image — black knit balaclava with red eye-slot, white hoodie, white shorts, chunky white boots and gloves.',
      'Now seated on a metal fire escape ledge in a slumped relaxed pose, one knee up, the other leg dangling off the edge.',
      'A lit cigarette held between two gloved fingers in his right hand, faint thin grey smoke trailing upward.',
      'Same flat 2D Markus Magnusson Sneaky-style cartoon rendering, same thick black ink outlines, same flat fill colors, same saturated purple background, same dotted floor shadows.',
    ].join(' '),
  },

  /**
   * THE DRIVER — cast pilot (Kontext, transformative).
   * Demonstrates using the anchor for STYLE/REGISTER carry-over while
   * transforming the character into a new entity. Heavy delta prompt.
   */
  theDriver: {
    key: 'theDriver',
    subject: 'THE DRIVER — chauffeur cousin of THE REGULAR',
    width: 1152,
    height: 864,
    seed: 4011,
    provider: 'replicate-flux-kontext-pro',
    anchorKey: 'theRegularBlack',
    prompt: [
      'Drawn in EXACTLY the same Markus Magnusson Sneaky cartoon style as the reference image — same thick black ink outlines, same flat fill, same chunky proportions, same saturated purple background, same dotted floor shadows.',
      'But this is a DIFFERENT character: a chauffeur. He wears a black peaked chauffeur cap pulled low over his face, a black knit balaclava with a single red eye-slot underneath the cap, a buttoned-up dark grey double-breasted chauffeur jacket with brass buttons, dark grey trousers, polished black shoes.',
      'He stands in a stiff three-quarter side stance holding a single brass car key dangling from one gloved finger.',
      'Same chunky white cartoon mitten gloves and same Mickey-style bulbous shoes as the reference (just black/dark instead of white).',
    ].join(' '),
  },

  /**
   * THE REGULAR — AT THE TABLE (Pool Hall County / The Players turf).
   * Anchor-driven Kontext slot. Uses SKIN_NEGATIVES inline to prevent the
   * leg-gap flesh hallucination surfaced by the fidelity test.
   */
  theRegularAtTheTable: {
    key: 'theRegularAtTheTable',
    subject: 'THE REGULAR — leaning over a pool table with a cue',
    width: 1152,
    height: 864,
    seed: 5101,
    provider: 'replicate-flux-kontext-pro',
    anchorKey: 'theRegularBlack',
    prompt: [
      'Same exact character from the reference image — black knit balaclava with the elongated horizontal red eye-slot and visible vertical knit ribbing, same baggy white pullover hoodie, same baggy white shorts, same chunky bulbous white Mickey-style boots, same big rounded white mitten gloves with no finger separation.',
      'Now leaning forward over a green felt pool table with both gloved hands resting on a wooden pool cue held horizontally across the table edge, head tilted down slightly as if lining up a shot, weight shifted onto the front foot with the back leg slightly extended.',
      'A small cube of blue chalk visible on the felt next to his hand. The wooden bumper rail of the pool table cropped at the bottom edge of the frame.',
      'Same flat 2D Markus Magnusson Sneaky cartoon style — same thick chunky black ink outlines with heavy line weight, same flat fill colors with zero shading, same saturated purple background visible above the pool table edge, same 3 to 5 small dark grey oval dot shadows scattered loosely on the floor beneath his feet.',
      SKIN_NEGATIVES,
    ].join(' '),
  },

  /**
   * THE REGULAR — IN THE BOOTH (Back Booth / Night Drinkers turf).
   * Closed food court energy. Anchor-driven Kontext.
   */
  theRegularInTheBooth: {
    key: 'theRegularInTheBooth',
    subject: 'THE REGULAR — slumped in a vinyl back booth, beer and food wrapper on the table',
    width: 1152,
    height: 864,
    seed: 5102,
    provider: 'replicate-flux-kontext-pro',
    anchorKey: 'theRegularBlack',
    prompt: [
      'Same exact character from the reference image — black knit balaclava with the elongated horizontal red eye-slot and visible vertical knit ribbing, same baggy white pullover hoodie, same baggy white shorts, same chunky bulbous white Mickey-style boots, same big rounded white mitten gloves with no finger separation.',
      'Now seated and slumped backward in a deep red vinyl diner-booth bench, one gloved arm draped lazily along the top edge of the booth backrest, the other hand resting on a formica table holding a half-crushed white paper food wrapper.',
      'A sweating silver-grey beer can on the table next to the wrapper. Visible vertical seams on the booth vinyl. The formica tabletop edge cropped along the bottom of the frame.',
      'Same flat 2D Markus Magnusson Sneaky cartoon style — same thick chunky black ink outlines, same flat fill colors with zero shading, same saturated purple background visible above the booth, same dotted floor shadows.',
      SKIN_NEGATIVES,
    ].join(' '),
  },

  /**
   * THE REGULAR — ON THE PHONE (Phone Behind The Bar callback).
   * Closed-food-court / motel-row register. Anchor-driven Kontext.
   */
  theRegularOnThePhone: {
    key: 'theRegularOnThePhone',
    subject: 'THE REGULAR — at a payphone, receiver pressed to the side of the balaclava',
    width: 1152,
    height: 864,
    seed: 5103,
    provider: 'replicate-flux-kontext-pro',
    anchorKey: 'theRegularBlack',
    prompt: [
      'Same exact character from the reference image — black knit balaclava with the elongated horizontal red eye-slot and visible vertical knit ribbing, same baggy white pullover hoodie, same baggy white shorts, same chunky bulbous white Mickey-style boots, same big rounded white mitten gloves with no finger separation.',
      'Now standing in a slight three-quarter side stance at a metal silver-grey payphone booth housing, with a black phone receiver pressed flat against the side of the balaclava held by his right gloved hand, the curly black phone cord coiling down from the receiver in loose loops.',
      'His left gloved hand rests flat against the silver metal phone box face. The payphone unit is visible from the waist up, mounted on a wall.',
      'Same flat 2D Markus Magnusson Sneaky cartoon style — same thick chunky black ink outlines, same flat fill colors with zero shading, same saturated purple background, same dotted floor shadows beneath his feet.',
      SKIN_NEGATIVES,
    ].join(' '),
  },

  /**
   * THE REGULAR — JUMPER variant (costume test).
   * Geometric fix for the skin-gap hallucination: replace hoodie+shorts with
   * a single-piece white jumpsuit (one continuous garment, no leg gap to fill).
   * If this lands and the silhouette still feels canonical, it could replace
   * hoodie+shorts as the standard outfit — at which point we re-render the
   * anchor itself in jumper form and update STYLE_ANCHORS.
   */
  theRegularJumper: {
    key: 'theRegularJumper',
    subject: 'THE REGULAR — costume test, single-piece white jumpsuit instead of hoodie+shorts',
    width: 1152,
    height: 864,
    seed: 5104,
    provider: 'replicate-flux-kontext-pro',
    anchorKey: 'theRegularBlack',
    prompt: [
      'Same exact character head from the reference image — black knit balaclava with the elongated horizontal red eye-slot, two glowing solid red eyes side by side, fully covered mouth and chin, visible vertical knit ribbing texture on the mask.',
      'Same chunky bulbous white Mickey-Mouse-style boots with rounded almost-spherical toes and no laces, same big rounded white cartoon mitten gloves with no finger separation.',
      'But the body is now wearing a single-piece baggy white pullover jumpsuit — ONE continuous unbroken white garment from below the mask all the way down to the boot tops, with NO waistband, NO belt, NO separation between top and bottom, NO visible hem at the waist, NO shorts. The white fabric runs straight from neckline to ankle in one piece, like a coverall or boiler suit, with a slight bunching at the wrists where the sleeves meet the gloves and at the ankles where the legs meet the boots.',
      'Same standing wide-stance pose from the reference. Same flat 2D Markus Magnusson Sneaky cartoon style — same thick chunky black ink outlines, same flat fill white with zero gradients and zero shading, same saturated purple background, same 3 to 5 small dark grey oval dot shadows on the floor.',
      'The character\'s entire body from neck to ankles is fully covered in unbroken flat white fabric. No skin tone, no bare wrists, no bare ankles, no flesh visible anywhere.',
    ].join(' '),
  },

  /**
   * MOTHIE — legacy moth mascot. Pre-generated via Replicate FLUX 1.1 Pro,
   * served from /public/void/mothie.jpg. Kept around but de-prioritized in
   * favor of THE REGULAR.
   */
  mothie: {
    key: 'mothie',
    subject: 'MOTHIE — kawaii moth mascot (legacy)',
    width: 896,
    height: 1152,
    seed: 4471,
    provider: 'replicate-flux-pro',
    prompt: [
      'A small chubby kawaii moth character with oversized fluffy wings and large round black eyes,',
      'pastel cream-colored body, soft fuzzy texture,',
      SHARED_STYLE,
    ].join(' '),
  },

  // =========================================================================
  // OMNISHIFT — fake-corporate-parent imagery (PR-L)
  // =========================================================================

  /**
   * OMNISHIFT — boardroom hero. Used on the corporate landing splash and
   * "About OmniShift" pages. The image any 2001 enterprise software vendor
   * would put above the fold. Slightly off-ness: one of the four people is
   * looking directly at the camera while the others look at the speaker.
   */
  omnishiftHeroBoardroom: {
    key: 'omnishiftHeroBoardroom',
    subject: 'OmniShift boardroom — four professionals around a conference table',
    width: 1280,
    height: 720,
    seed: 6001,
    provider: 'replicate-flux-pro',
    prompt: [
      'Four multi-ethnic business professionals in their thirties seated around a faux-mahogany oval conference table in a corporate office, taken from a slight low-angle three-quarter view.',
      'Three of them have eyes turned attentively toward an unseen speaker at the head of the table; ONE of them — the woman in the navy blazer — is looking directly at the camera with a held smile that is just slightly too long.',
      'They wear early-2000s business-casual: collared oxford shirts in white and pale blue, navy blazers, one striped tie. A beige Dell PC tower with a green LED is barely visible in the background corner. A laser-printed memo and a Styrofoam coffee cup sit on the table.',
      OMNISHIFT_REGISTER,
    ].join(' '),
  },

  /**
   * OMNISHIFT — close-up handshake hero. Generic enterprise stock-photo
   * cliché. The kind of image used on "Partnerships" or "Our Promise" pages.
   * Off-ness: the third hand entering the frame from the left.
   */
  omnishiftHeroHandshake: {
    key: 'omnishiftHeroHandshake',
    subject: 'OmniShift partnership handshake — close-up of two pairs of business hands',
    width: 1280,
    height: 720,
    seed: 6002,
    provider: 'replicate-flux-pro',
    prompt: [
      'Tight close-up photograph of a business handshake between two pairs of hands. The left hand wears a starched white oxford-shirt cuff with a silver wristwatch; the right hand wears a pale-blue oxford cuff with a gold pinky ring. Their palms are joined firmly, fingers wrapping.',
      'Slightly out of focus in the upper-left edge of the frame, a THIRD hand is just entering the shot — only the fingertips visible, palm-up, as if waiting its turn or interrupting.',
      'Background is an out-of-focus navy-to-cyan corporate gradient with a faint OmniShift logo bug ghosted in the lower-right corner — just a dimensional sans-serif "OmniShift" wordmark in muted IBM-blue.',
      OMNISHIFT_REGISTER,
    ].join(' '),
  },

  /**
   * OMNISHIFT — generic employee portrait clip-art. Used as the default
   * placeholder for Employee File pages when no profile photo is available.
   * Recraft V3 with vector_illustration/cartoon for clean clip-art register.
   */
  omnishiftEmployeePortraitDefault: {
    key: 'omnishiftEmployeePortraitDefault',
    subject: 'Default OmniShift employee placeholder portrait — generic businessperson clip art',
    width: 1024,
    height: 1024,
    seed: 6003,
    provider: 'replicate-recraft-v3',
    recraftStyle: 'vector_illustration/cartoon',
    prompt: [
      'A generic clip-art-style vector illustration of a business professional from the chest up, facing forward with a neutral pleasant expression.',
      'Wearing a white collared shirt with a navy IBM-blue tie. Short brown hair, ambiguous gender, ambiguous ethnicity — the kind of "everyperson" placeholder figure used in stock corporate clip-art collections from 2001.',
      'Flat 2D vector illustration with a thin black outline and limited color palette (5 to 6 colors maximum). Background is a flat cream-white. No gradients, no shading except a single flat shadow on the neck.',
      'Cheap clip-art register — this is the kind of figure that appears in a Microsoft Office 2001 ClipArt Gallery search for "businessperson". Friendly but generic, slightly stiff, suitable for a placeholder.',
    ].join(' '),
  },

  // =========================================================================
  // SLEEPNET PORTAL — old-web directory imagery (PR-L)
  // =========================================================================

  /**
   * SLEEPNET — directory clerk mascot. Pictures the imagined "person who
   * indexes the after-hours internet" — bored, fluorescent-lit, surrounded
   * by file folders. Recraft V3 for native flat-illustration prior.
   */
  sleepnetDirectoryClerk: {
    key: 'sleepnetDirectoryClerk',
    subject: 'SleepNet directory clerk mascot — illustrated character at a glowing CRT terminal',
    width: 1024,
    height: 1024,
    seed: 6101,
    provider: 'replicate-recraft-v3',
    recraftStyle: 'digital_illustration/2d_art_poster',
    prompt: [
      'A bored cartoon clerk character seated at a beige CRT computer terminal, viewed from a three-quarter angle. The clerk wears a green plastic visor on his forehead, black arm garters on his rolled-up white shirt sleeves, and round wire-frame glasses. He has a thin moustache and tired half-closed eyes.',
      'Stacks of manila file folders are piled high on either side of the terminal, each labeled with a small handwritten tag. The CRT screen glows green with cryptic text. A single naked fluorescent tube hangs above him.',
      'A small enamel pin on his shirt collar reads "SleepNet · Indexing Division".',
      SLEEPNET_PORTAL_REGISTER,
    ].join(' '),
  },

  /**
   * SLEEPNET — web ring banner badge. Tiny composite graphic in the
   * Geocities 1999 web ring style. 88x31 banner-ad proportions but rendered
   * larger so it can be downscaled cleanly.
   */
  sleepnetWebRingBadge: {
    key: 'sleepnetWebRingBadge',
    subject: 'SleepNet web ring banner badge — 1999 Geocities-era ring graphic',
    width: 1024,
    height: 360,
    seed: 6102,
    provider: 'replicate-recraft-v3',
    recraftStyle: 'vector_illustration/flat_2',
    prompt: [
      'A horizontal banner-ad-shaped graphic in the exact style of a 1999 Geocities web ring banner — proportioned roughly 1024 by 360 pixels but rendered in the visual register of the original 88x31 GIF banner ads of that era.',
      'Left third: a small cartoon moon-and-stars icon in saturated GIF yellow on black. Center third: chunky pixelated bitmap text reading "JOIN THE CIRCLE" in alternating Yahoo purple and saturated red, with a slight 1-pixel drop shadow. Right third: small triangular "← PREV / NEXT →" navigation arrows in white on a deep blue panel.',
      'Hard edges, no anti-aliasing, no gradients — pure 4-color GIF palette (purple, red, yellow, white) on a black background with a 2-pixel beveled outer border in dark grey.',
      SLEEPNET_PORTAL_REGISTER,
    ].join(' '),
  },

  // =========================================================================
  // VERY GOOD BURGER — fake fast-food chain (PR-L)
  // =========================================================================

  /**
   * VGB — Billy the burger mascot. Anthropomorphic burger character. Should
   * read as a knockoff "Billy Burger" from a regional chain that nobody
   * remembers. Friendly, slightly too eager.
   */
  vgbMascotBilly: {
    key: 'vgbMascotBilly',
    subject: 'BILLY the Very Good Burger mascot — anthropomorphic cartoon burger character',
    width: 1024,
    height: 1280,
    seed: 6201,
    provider: 'replicate-recraft-v3',
    recraftStyle: 'digital_illustration/hand_drawn',
    prompt: [
      'A friendly anthropomorphic cartoon hamburger mascot character standing facing the camera with one tiny white-gloved hand raised in a wave.',
      'The character\'s body is a single sesame-seed bun with cartoon eyes (large, white, with small black pupils and one off-center) on the top bun half, a wide friendly mouth across the middle (the burger patty layer), and a thin layer of melted cheese drooping at the corners.',
      'The sesame seeds on the top bun are arranged in a slightly off-symmetric pattern — they look like freckles. Tiny white-gloved hands, tiny white-booted feet, no visible legs or arms beyond the gloves and boots (rubber hose limbs implied).',
      'A small red banner above his head reads "VERY GOOD!" in bold uppercase marker text with a slight drop shadow.',
      'Standing on a flat yellow background with a single pencil-shadow at his feet. Drawn in the register of a 1999 regional fast-food chain mascot — friendlier than McDonald\'s, cheaper than Disney, the kind of mascot that appeared on the side of a Styrofoam cup in a mall food court.',
      'Ink outlines, flat fill, no gradients. Sized for use as a hero illustration on a "Welcome to Very Good Burger" page.',
    ].join(' '),
  },

  /**
   * VGB — glamour-shot burger. The catalog hero. Required off-ness: wilted
   * brown lettuce edges. Reads as "real burger photo from a 2001 menu" but
   * nags at the viewer.
   */
  vgbHeroBurger: {
    key: 'vgbHeroBurger',
    subject: 'VGB hero burger — glamour photo of a single Very Good Burger',
    width: 1280,
    height: 960,
    seed: 6202,
    provider: 'replicate-flux-pro',
    prompt: [
      'A single hamburger photographed dead-center on a plain white plate, viewed from a low three-quarter angle. The bun is a sesame-seed top bun, slightly asymmetric (one side a touch taller than the other). A beef patty is visible with a thin layer of melted American cheese drooping over one edge in a frozen mid-drip.',
      'Below the cheese, a layer of green-leaf lettuce — and CRITICALLY, the visible edges of the lettuce are slightly wilted and turning brown at the very tips, which is the off-ness signal for this image. Below the lettuce, a single ring of red onion and a thick slice of tomato.',
      'A faint wisp of steam rises from the patty. The plate sits on a red-and-yellow checked paper liner. Background is out-of-focus warm yellow chain-restaurant interior with a hint of red vinyl booth.',
      VGB_REGISTER,
    ].join(' '),
  },

  /**
   * VGB — drive-thru family. The "we love serving families fast" stock shot.
   * Off-ness: child in the back has a slightly too-wide smile.
   */
  vgbDriveThruFamily: {
    key: 'vgbDriveThruFamily',
    subject: 'VGB drive-thru family — multi-ethnic family at the pickup window',
    width: 1280,
    height: 720,
    seed: 6203,
    provider: 'replicate-flux-pro',
    prompt: [
      'A multi-ethnic family of four (a man and woman in their mid-30s in the front seats, a boy around 8 and a girl around 6 in the back seat) seated in a beige minivan at a fast-food drive-thru pickup window. The window is glowing with warm yellow fluorescent light from inside the restaurant. A masked employee\'s gloved hand is just visible passing a brown paper bag stamped with the red "Very Good Burger" wordmark.',
      'The mother is paying with a credit card; the father is smiling and giving a thumbs-up to the camera; the daughter is reaching for the bag.',
      'CRITICAL OFF-NESS: the BOY in the back seat has a smile that is just slightly too wide for his face — about 15% wider than natural — but otherwise looks normal.',
      'Sun-drenched suburban parking lot, mid-afternoon, slight lens flare. Photograph style: stock-photo cheerfulness, slightly too-bright on highlights.',
      VGB_REGISTER,
    ].join(' '),
  },

  // =========================================================================
  // SLEEPNEWS — fake-newspaper photography (PR-L)
  // =========================================================================

  /**
   * SLEEPNEWS — incident press photo. Generic candid-news-photo for ambient
   * article hero use. Composition is intentionally slightly off, the way
   * real wire-service photos often are.
   */
  slpnewsHeroIncident: {
    key: 'slpnewsHeroIncident',
    subject: 'SleepNews incident hero — grainy nighttime press photo of a parking lot scene',
    width: 1280,
    height: 854,
    seed: 6301,
    provider: 'replicate-flux-pro',
    prompt: [
      'A nighttime press photograph of an empty motel parking lot, taken with a flash. Two distant figure silhouettes are barely visible standing near a cone of light beneath a tall sodium-vapor streetlamp at the far end of the lot, their faces obscured by shadow.',
      'In the upper-left edge of the frame, a partially cut-off motel sign with neon tube letters reads "MOT", the rest cropped out — only "MOT" is visible. A No Parking sign on a rust-streaked metal post pokes into the lower-right edge of the frame.',
      'A single Pepsi can lies on its side in the foreground asphalt. The asphalt has irregular puddles reflecting the orange streetlamp light.',
      'Captured on a 35mm camera with on-camera flash bouncing off a row of parked cars in the middle distance — the flash creates a hot spot on one car\'s rear windshield. The ground in the foreground is darker than the background due to the inverse-square falloff.',
      SLEEPNEWS_REGISTER,
    ].join(' '),
  },

  /**
   * SLEEPNEWS — correction stamp. Recurring graphic for the in-world
   * "correction filed but not applied" copy throughout the SleepNews paper.
   * Recraft for native paper-and-grain register.
   */
  slpnewsCorrectionStamp: {
    key: 'slpnewsCorrectionStamp',
    subject: 'SleepNews correction stamp — typewritten correction notice with red rubber stamp',
    width: 1024,
    height: 768,
    seed: 6302,
    provider: 'replicate-recraft-v3',
    recraftStyle: 'digital_illustration/grain',
    prompt: [
      'A close-up illustration of a small piece of off-white newsprint paper with three lines of typewritten text in black IBM Selectric typeface reading "CORRECTION:" on line one, then "FILED BUT" on line two, then "NOT APPLIED" on line three.',
      'A bold red rubber-stamp impression has been pressed diagonally across the top-right corner of the paper, the stamp reading "RECEIVED · SLEEPNEWS · DESK 4" in an irregular cracked-ink texture (some letters faded, some over-saturated).',
      'The paper has subtle horizontal newsprint dot pattern visible across its surface, plus a faint single coffee-cup-ring stain in the lower-left.',
      'The paper is slightly rotated counterclockwise about 4 degrees, casting a soft shadow on a dark wood desk surface beneath it. A typewriter ribbon spool sits out of focus in the upper edge of the frame.',
      SLEEPNEWS_REGISTER,
    ].join(' '),
  },
};

// ---------------------------------------------------------------------------
// URL builders + dispatcher
// ---------------------------------------------------------------------------

const POLLINATIONS_BASE = 'https://image.pollinations.ai/prompt';
const URL_CEILING = 1700;

function buildPollinationsUrl(p: NanoPrompt, model: string): string {
  // Trim prompt to fit under URL ceiling once encoded + model/size/seed params.
  const params = `?width=${p.width}&height=${p.height}&seed=${p.seed}&model=${model}&nologo=true`;
  const encodedBudget = URL_CEILING - POLLINATIONS_BASE.length - params.length - 10;
  const encoded = encodeURIComponent(p.prompt);
  const trimmed =
    encoded.length > encodedBudget ? encoded.slice(0, encodedBudget) : encoded;
  return `${POLLINATIONS_BASE}/${trimmed}${params}`;
}

export const pollinationsFluxUrl = (p: NanoPrompt) => buildPollinationsUrl(p, 'flux');
export const pollinationsRealismUrl = (p: NanoPrompt) =>
  buildPollinationsUrl(p, 'flux-realism');
export const pollinationsTurboUrl = (p: NanoPrompt) => buildPollinationsUrl(p, 'turbo');
export const pollinationsGptImageUrl = (p: NanoPrompt) =>
  buildPollinationsUrl(p, 'gptimage');

/**
 * Pre-generated slots and static assets all resolve to a committed binary
 * at /public/void/<key>.jpg. The regen script (or you, manually) writes that
 * file; the dispatcher just returns its path.
 */
export function staticAssetUrl(p: NanoPrompt): string {
  return `/void/${p.key}.jpg`;
}

/** Master dispatcher — routes each slot to its declared provider. */
export function imageUrl(p: NanoPrompt): string {
  switch (p.provider) {
    case 'pollinations-flux':
      return pollinationsFluxUrl(p);
    case 'pollinations-realism':
      return pollinationsRealismUrl(p);
    case 'pollinations-turbo':
      return pollinationsTurboUrl(p);
    case 'pollinations-gptimage':
      return pollinationsGptImageUrl(p);
    // All paid providers + static-asset serve from the same committed-binary
    // path. The differences (which model generates, whether img2img, etc.)
    // matter only at regen time — not at request/render time.
    case 'replicate-flux-pro':
    case 'replicate-flux-dev':
    case 'replicate-flux-kontext-pro':
    case 'replicate-recraft-v3':
    case 'replicate-sdxl':
    case 'replicate-imagen':
    case 'static-asset':
      return staticAssetUrl(p);
  }
}

/** Convenience: get a slot by key. Throws if missing — fail fast on typos. */
export function getNanoPrompt(key: string): NanoPrompt {
  const p = NANO_PROMPTS[key];
  if (!p) throw new Error(`[nanoPrompts] Unknown slot key: ${key}`);
  return p;
}
